@baseUrl = http://localhost:3000

###
# @name login
POST {{baseUrl}}/login
# you can't add a blank line here
Content-Type: application/json

{
  "username": "test1",
  "password": "123456"
}


###
# @name login-token
POST {{baseUrl}}/login-token
# you can't add a blank line here
Content-Type: application/json

{
  "username": "test1",
  "password": "123456"
}


###
GET {{baseUrl}}/list
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInVzZXJuYW1lIjoidGVzdDEiLCJpYXQiOjE3NTYyNDc2ODUsImV4cCI6MTc1NjI1MTI4NX0.YMYRUhojwoMd1lfhK1mxOPBYwig_Pa-8Tkta93uGNMI

###
GET {{baseUrl}}/public
# 访问使用@IsPublic()装饰器的接口，不进行JwtAuthGuard的认证


###
GET {{baseUrl}}/bbb
# 访问没有使用@IsPublic()装饰器的接口，返回401错误；


###
# github login
GET {{baseUrl}}/github-login